### PR TITLE
Refactor git install and update

### PR DESCRIPTION
**Pull request by dmitryilyin**
- Use the same procedure for git install and update
- Support fetching of tags and branches
- Support Gerrit's refs/changes/?/? branches

### CODE REVIEW

**Comment by dmitryilyin** [comment]
This may be a better solution and it also does this https://github.com/bodepd/librarian-puppet-simple/pull/33

**Comment by dmitryilyin** [comment]
Hello?

**Comment by dmitryilyin** [comment]
@bodepd Hello, look at this, please

**Comment by ghoneycutt** [comment]
Closing due to inactivity.

**Pull request closed without merging**
